export const ERROR_CODES = {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    NOT_UNIQUE: 'NOT_UNIQUE',
    AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
    NOT_EQUAL: 'NOT_EQUAL',
    REQUIRED: 'REQUIRED',
    FORMAT_ERROR: 'FORMAT_ERROR',
    EXISTS: 'EXISTS',
    UNNECESARY: 'UNNECESSARY',
};
